[package]
name = "digital_vault"
version = "1.0.0"
authors = ["Digital Vault Team"]

[addresses]
digital_vault = "_"

[dev-addresses]
digital_vault = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]